const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Jammanna_MakeIt3D,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Jammanna_MakeIt3D.Acts.CreateScene,
		C3.Plugins.Jammanna_MakeIt3D.Acts.SetOrbitControlProps,
		C3.Plugins.Jammanna_MakeIt3D.Exps.Vector3,
		C3.Plugins.Jammanna_MakeIt3D.Acts.LoadCustomModel,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Jammanna_MakeIt3D.Acts.PlayAnimationClip,
		C3.Plugins.Jammanna_MakeIt3D.Acts.AddPlane,
		C3.Plugins.Jammanna_MakeIt3D.Exps.RGB,
		C3.Plugins.Jammanna_MakeIt3D.Acts.SetTextureWrap,
		C3.Plugins.Jammanna_MakeIt3D.Acts.SetTextureRepeat,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Jammanna_MakeIt3D.Acts.AddCube,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Jammanna_MakeIt3D.Cnds.IsObjectLoaded,
		C3.Plugins.Jammanna_MakeIt3D.Acts.SetObjectPositionX,
		C3.Plugins.Jammanna_MakeIt3D.Exps.PositionX,
		C3.Plugins.Jammanna_MakeIt3D.Acts.SetObjectPositionZ,
		C3.Plugins.Jammanna_MakeIt3D.Exps.PositionZ,
		C3.Plugins.Jammanna_MakeIt3D.Acts.ObjectLookAt,
		C3.Plugins.Jammanna_MakeIt3D.Exps.PositionY,
		C3.Plugins.Jammanna_MakeIt3D.Acts.CameraLookAtObject,
		C3.Plugins.Jammanna_MakeIt3D.Acts.SetCameraFollowObject,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{MakeIt3D: 0},
	{Keyboard: 0},
	{Text: 0},
	{drag: 0},
	{Drag: 0},
	{DragDrop: 0},
	{bg: 0},
	{distance: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Touch: 0},
	{dirfb: 0},
	{isJumping: 0},
	{AnimationState: 0},
	{dirrl: 0},
	{AnimationNumber: 0}
];

self.InstanceType = {
	MakeIt3D: class extends C3.Plugins.Jammanna_MakeIt3D.Instance {},
	Keyboard: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Drag: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {}
}