const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Jammanna_MakeIt3D,
		C3.Plugins.MakeIt3D_Object,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.wrap,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Jammanna_MakeIt3D.Acts.CreateScene,
		C3.Plugins.Jammanna_MakeIt3D.Acts.SetSceneFog,
		C3.Plugins.Jammanna_MakeIt3D.Exps.RGB,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Jammanna_MakeIt3D.Acts.AddDirectionalLight,
		C3.Plugins.Jammanna_MakeIt3D.Exps.Vector3,
		C3.Plugins.Jammanna_MakeIt3D.Acts.SetDirectionalShadowBounds,
		C3.Plugins.Jammanna_MakeIt3D.Acts.SetLightShadowResolution,
		C3.Plugins.Jammanna_MakeIt3D.Acts.SetLightShadowBias,
		C3.Plugins.Jammanna_MakeIt3D.Acts.AddAmbientLight,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.MakeIt3D_Object.Acts.SetRotationX,
		C3.Plugins.MakeIt3D_Object.Acts.AddInstanceVar,
		C3.Plugins.Jammanna_MakeIt3D.Acts.SetCameraPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Jammanna_MakeIt3D.Acts.SetCameraAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Cnds.CompareTouchSpeed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.System.Exps.max
	];
};
self.C3_JsPropNameTable = [
	{MakeIt3D: 0},
	{Rotate: 0},
	{Sine: 0},
	{Ground: 0},
	{trees: 0},
	{x_rot: 0},
	{windmill_rotar: 0},
	{woodenHouse: 0},
	{touchStartX: 0},
	{"8Direction": 0},
	{Wrap: 0},
	{Camera: 0},
	{key: 0},
	{ArrowKey: 0},
	{Button: 0},
	{Touch: 0},
	{rock: 0},
	{TouchX: 0},
	{Y_Rotation: 0},
	{TouchY: 0},
	{sensitivity: 0},
	{isMoving: 0}
];

self.InstanceType = {
	MakeIt3D: class extends C3.Plugins.Jammanna_MakeIt3D.Instance {},
	Ground: class extends C3.Plugins.MakeIt3D_Object.Instance {},
	trees: class extends C3.Plugins.MakeIt3D_Object.Instance {},
	windmill_rotar: class extends C3.Plugins.MakeIt3D_Object.Instance {},
	woodenHouse: class extends C3.Plugins.MakeIt3D_Object.Instance {},
	Camera: class extends self.ISpriteInstance {},
	ArrowKey: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Touch: class extends self.IInstance {},
	rock: class extends C3.Plugins.MakeIt3D_Object.Instance {}
}